DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS challenges;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT, 
  username VARCHAR(15) UNIQUE NOT NULL,
  password VARCHAR(30) NOT NULL
);

CREATE TABLE challenges (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  task TEXT NOT NULL,
  time_allocated INTEGER NOT NULL,
  time_finished INTEGER NOT NULL,
  complete TINYINT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
)
